"""
Bounded Cache Module for SpacetimeDB SDK

Provides core caching functionality with bounded storage and memory management.
This module extracts the caching logic from bounded_client_cache.py for better
separation of concerns.
"""

import importlib
import pkgutil
import logging
from .utils.error_formatting import ErrorFormatter
import threading
import time
from typing import Dict, List, Optional, Any, Callable
from dataclasses import dataclass

from .memory_management import (
    BoundedDict, MemoryAccountant, get_global_memory_accountant,
    DEFAULT_MAX_CACHE_SIZE
)

logger = logging.getLogger(__name__)


def snake_to_camel(snake_case_string: str) -> str:
    """Convert snake_case to CamelCase."""
    return snake_case_string.replace("_", " ").title().replace(" ", "")


class BoundedTableCache:
    """
    Table cache with bounded storage and memory management.
    
    Features:
    - Maximum entry limit
    - Memory accounting
    - Automatic eviction on memory pressure
    """
    
    def __init__(
        self,
        table_class,
        max_entries: int = DEFAULT_MAX_CACHE_SIZE,
        memory_accountant: Optional[MemoryAccountant] = None
    ):
        self.table_class = table_class
        self.memory_accountant = memory_accountant or get_global_memory_accountant()
        
        def on_evict(key, value):
            logger.debug(f"Evicted cache entry for table {self.table_class.__name__}: {key}")
        
        self.entries = BoundedDict(
            max_size=max_entries,
            memory_accountant=self.memory_accountant,
            on_evict=on_evict
        )
    
    def decode(self, value: Any) -> Any:
        """Decode a value using the table class."""
        return self.table_class(value)
    
    def set_entry(self, key: Any, value: Any) -> None:
        """Set an entry after decoding."""
        try:
            decoded_value = self.decode(value)
            self.entries.set(key, decoded_value)
        except Exception as e:
            logger.error(ErrorFormatter.format_cache_error(f"decode and cache entry for key {key}", e))
    
    def set_entry_decoded(self, key: Any, decoded_value: Any) -> None:
        """Set an already decoded entry."""
        self.entries.set(key, decoded_value)
    
    def delete_entry(self, key: Any) -> bool:
        """Delete an entry."""
        if self.entries.delete(key):
            return True
        else:
            logger.warning(f"[delete_entry] Key not found: {key}")
            return False
    
    def get_entry(self, key: Any) -> Optional[Any]:
        """Get an entry."""
        return self.entries.get(key)
    
    def values(self):
        """Get all cached values."""
        return self.entries.values()
    
    def get_stats(self) -> Dict[str, Any]:
        """Get cache statistics."""
        return {
            'entry_count': len(self.entries),
            'table_class': self.table_class.__name__
        }


class BoundedClientCache:
    """
    Combined client cache with bounded storage for tables/reducers and context pooling.
    
    Features:
    - Bounded table caches with memory management
    - Bounded reducer cache
    - Client caching with TTL
    - Memory accounting and statistics
    """
    
    def __init__(
        self,
        autogen_package=None,
        max_cache_size: int = DEFAULT_MAX_CACHE_SIZE,
        memory_accountant: Optional[MemoryAccountant] = None,
        max_clients: int = 100,
        ttl_seconds: float = 300.0
    ):
        self.memory_accountant = memory_accountant or get_global_memory_accountant()
        self.max_cache_size = max_cache_size
        self.max_clients = max_clients
        self.ttl_seconds = ttl_seconds
        
        # Bounded storage for tables and reducers
        self.tables: Dict[str, BoundedTableCache] = {}
        self.reducer_cache = BoundedDict(
            max_size=1000,  # Reasonable limit for reducers
            memory_accountant=self.memory_accountant
        )
        
        # Client cache
        self._clients: Dict[str, Any] = {}
        self._client_timestamps: Dict[str, float] = {}
        self._lock = threading.RLock()
        
        # Cleanup thread
        self._cleanup_thread = threading.Thread(target=self._cleanup_loop, daemon=True)
        self._cleanup_running = True
        self._cleanup_thread.start()
        
        self.logger = logging.getLogger(f"{__name__}.BoundedClientCache")
        
        # Load tables and reducers from autogen package if provided
        if autogen_package:
            self._load_autogen_package(autogen_package)
    
    def _load_autogen_package(self, autogen_package) -> None:
        """Load tables and reducers from autogenerated package."""
        try:
            for importer, module_name, is_package in pkgutil.iter_modules(
                autogen_package.__path__
            ):
                if not is_package:
                    module = importlib.import_module(
                        f"{autogen_package.__name__}.{module_name}"
                    )
                    
                    # Check if it's a reducer
                    if module_name.endswith("_reducer"):
                        reducer_name = getattr(module, "reducer_name", None)
                        args_class = getattr(module, "_decode_args", None)
                        
                        if reducer_name and args_class:
                            self.reducer_cache.set(reducer_name, args_class)
                            logger.debug(f"Loaded reducer: {reducer_name}")
                    else:
                        # Assuming table class name is the same as the module name
                        table_class_name = snake_to_camel(module_name)
                        
                        if hasattr(module, table_class_name):
                            table_class = getattr(module, table_class_name)
                            
                            # Check for a special property, e.g. 'is_table_class'
                            if getattr(table_class, "is_table_class", False):
                                self.tables[table_class_name] = BoundedTableCache(
                                    table_class,
                                    max_entries=self.max_cache_size,
                                    memory_accountant=self.memory_accountant
                                )
                                logger.debug(f"Loaded table: {table_class_name}")
        
        except Exception as e:
            logger.error(ErrorFormatter.format_generic_error("Cache", "autogen package loading", e))
    
    def _cleanup_loop(self) -> None:
        """Background cleanup of expired clients."""
        while self._cleanup_running:
            try:
                self._cleanup_expired_clients()
                time.sleep(30)  # Check every 30 seconds
            except Exception as e:
                self.logger.error(ErrorFormatter.format_cache_error("cleanup", e))
    
    def _cleanup_expired_clients(self) -> None:
        """Remove expired clients from cache."""
        current_time = time.time()
        expired_keys = []
        
        with self._lock:
            for key, timestamp in self._client_timestamps.items():
                if current_time - timestamp > self.ttl_seconds:
                    expired_keys.append(key)
            
            for key in expired_keys:
                if key in self._clients:
                    del self._clients[key]
                    del self._client_timestamps[key]
        
        if expired_keys:
            self.logger.info(f"Cleaned up {len(expired_keys)} expired clients")
    
    def get_table_cache(self, table_name: str) -> Optional[BoundedTableCache]:
        """Get table cache by name."""
        return self.tables.get(table_name)
    
    def decode(self, table_name: str, value: Any) -> Optional[Any]:
        """Decode a value for a specific table."""
        if table_name not in self.tables:
            logger.error(ErrorFormatter.format_cache_error(f"decode table {table_name}", Exception(f"Table not found: {table_name}")))
            return None
        
        try:
            return self.tables[table_name].decode(value)
        except Exception as e:
            logger.error(ErrorFormatter.format_cache_error(f"decode value for table {table_name}", e))
            return None
    
    def set_entry(self, table_name: str, key: Any, value: Any) -> bool:
        """Set an entry in a table cache."""
        if table_name not in self.tables:
            logger.error(ErrorFormatter.format_cache_error(f"set entry for table {table_name}", Exception(f"Table not found: {table_name}")))
            return False
        
        try:
            self.tables[table_name].set_entry(key, value)
            return True
        except Exception as e:
            logger.error(ErrorFormatter.format_cache_error(f"set entry for table {table_name}", e))
            return False
    
    def set_entry_decoded(self, table_name: str, key: Any, value: Any) -> bool:
        """Set an already decoded entry in a table cache."""
        if table_name not in self.tables:
            logger.error(ErrorFormatter.format_cache_error(f"set decoded entry for table {table_name}", Exception(f"Table not found: {table_name}")))
            return False
        
        try:
            self.tables[table_name].set_entry_decoded(key, value)
            return True
        except Exception as e:
            logger.error(ErrorFormatter.format_cache_error(f"set decoded entry for table {table_name}", e))
            return False
    
    def delete_entry(self, table_name: str, key: Any) -> bool:
        """Delete an entry from a table cache."""
        if table_name not in self.tables:
            logger.error(ErrorFormatter.format_cache_error(f"delete entry for table {table_name}", Exception(f"Table not found: {table_name}")))
            return False
        
        return self.tables[table_name].delete_entry(key)
    
    def get_entry(self, table_name: str, key: Any) -> Optional[Any]:
        """Get an entry from a table cache."""
        if table_name not in self.tables:
            logger.error(ErrorFormatter.format_cache_error(f"get entry for table {table_name}", Exception(f"Table not found: {table_name}")))
            return None
        
        return self.tables[table_name].get_entry(key)
    
    def get_client(self, client_id: str) -> Optional[Any]:
        """Get a client from the cache."""
        with self._lock:
            if client_id in self._clients:
                # Update timestamp
                self._client_timestamps[client_id] = time.time()
                return self._clients[client_id]
            return None
    
    def put_client(self, client_id: str, client: Any) -> None:
        """Put a client in the cache."""
        with self._lock:
            # Remove oldest client if at capacity
            if len(self._clients) >= self.max_clients:
                oldest_key = min(self._client_timestamps.keys(), 
                               key=lambda k: self._client_timestamps[k])
                del self._clients[oldest_key]
                del self._client_timestamps[oldest_key]
            
            self._clients[client_id] = client
            self._client_timestamps[client_id] = time.time()
    
    def get_cache_stats(self) -> Dict[str, Any]:
        """Get comprehensive cache statistics."""
        memory_stats = self.memory_accountant.get_stats()
        
        table_stats = {}
        for table_name, table_cache in self.tables.items():
            table_stats[table_name] = table_cache.get_stats()
        
        return {
            'memory_usage': {
                'total_bytes': memory_stats.total_bytes,
                'cache_bytes': memory_stats.cache_bytes,
                'peak_bytes': memory_stats.peak_bytes,
                'evictions': memory_stats.evictions,
                'oom_prevented': memory_stats.oom_prevented,
                'usage_percentage': self.memory_accountant.get_usage_percentage()
            },
            'table_caches': table_stats,
            'reducer_cache': {
                'entry_count': len(self.reducer_cache)
            },
            'client_cache': {
                'client_count': len(self._clients)
            }
        }
    
    def clear_all_caches(self) -> None:
        """Clear all caches."""
        for table_cache in self.tables.values():
            table_cache.entries.clear()
        
        self.reducer_cache.clear()
        
        with self._lock:
            self._clients.clear()
            self._client_timestamps.clear()
        
        logger.info("All caches cleared")
    
    def cleanup_memory_pressure(self) -> Dict[str, int]:
        """Perform cleanup when under memory pressure."""
        cleared_counts = {}
        
        # Clear least important caches first
        for table_name, table_cache in self.tables.items():
            old_count = len(table_cache.entries)
            # Force eviction of half the entries by temporarily reducing size
            original_size = table_cache.entries._max_size
            table_cache.entries._max_size = original_size // 2
            table_cache.entries._evict_if_needed()
            table_cache.entries._max_size = original_size
            
            cleared_count = old_count - len(table_cache.entries)
            if cleared_count > 0:
                cleared_counts[table_name] = cleared_count
        
        return cleared_counts
    
    def shutdown(self) -> None:
        """Shutdown the cache and cleanup resources."""
        self._cleanup_running = False
        if self._cleanup_thread.is_alive():
            self._cleanup_thread.join(timeout=5)
        
        self._clients.clear()
        self._client_timestamps.clear()
        
        self.logger.info("BoundedClientCache shutdown complete")


# For backward compatibility, provide the same interface as the original client_cache
ClientCache = BoundedClientCache
TableCache = BoundedTableCache