"""
Bounded client cache implementation with memory management.

This replaces the unbounded client_cache.py with memory-safe bounded collections.
"""

import importlib
import pkgutil
import logging
from typing import Dict, Any, Optional

from .memory_management import (
    BoundedDict, MemoryAccountant, get_global_memory_accountant,
    DEFAULT_MAX_CACHE_SIZE
)

logger = logging.getLogger(__name__)


def snake_to_camel(snake_case_string: str) -> str:
    """Convert snake_case to CamelCase."""
    return snake_case_string.replace("_", " ").title().replace(" ", "")


class BoundedTableCache:
    """
    Table cache with bounded storage and memory management.
    
    Features:
    - Maximum entry limit
    - Memory accounting
    - Automatic eviction on memory pressure
    """
    
    def __init__(
        self,
        table_class,
        max_entries: int = DEFAULT_MAX_CACHE_SIZE,
        memory_accountant: Optional[MemoryAccountant] = None
    ):
        self.table_class = table_class
        self.memory_accountant = memory_accountant or get_global_memory_accountant()
        
        def on_evict(key, value):
            logger.debug(f"Evicted cache entry for table {self.table_class.__name__}: {key}")
        
        self.entries = BoundedDict(
            max_size=max_entries,
            memory_accountant=self.memory_accountant,
            on_evict=on_evict
        )
    
    def decode(self, value: Any) -> Any:
        """Decode a value using the table class."""
        return self.table_class(value)
    
    def set_entry(self, key: Any, value: Any) -> None:
        """Set an entry after decoding."""
        try:
            decoded_value = self.decode(value)
            self.entries.set(key, decoded_value)
        except Exception as e:
            logger.error(f"Failed to decode and cache entry for key {key}: {e}")
    
    def set_entry_decoded(self, key: Any, decoded_value: Any) -> None:
        """Set an already decoded entry."""
        self.entries.set(key, decoded_value)
    
    def delete_entry(self, key: Any) -> bool:
        """Delete an entry."""
        if self.entries.delete(key):
            return True
        else:
            logger.warning(f"[delete_entry] Key not found: {key}")
            return False
    
    def get_entry(self, key: Any) -> Optional[Any]:
        """Get an entry."""
        return self.entries.get(key)
    
    def values(self):
        """Get all cached values."""
        return self.entries.values()
    
    def get_stats(self) -> Dict[str, Any]:
        """Get cache statistics."""
        return {
            'entry_count': len(self.entries),
            'table_class': self.table_class.__name__
        }


class BoundedClientCache:
    """
    Client cache with bounded storage for tables and reducers.
    
    Features:
    - Bounded table caches
    - Bounded reducer cache
    - Memory accounting
    - Cache statistics
    """
    
    def __init__(
        self,
        autogen_package,
        max_cache_size: int = DEFAULT_MAX_CACHE_SIZE,
        memory_accountant: Optional[MemoryAccountant] = None
    ):
        self.memory_accountant = memory_accountant or get_global_memory_accountant()
        self.max_cache_size = max_cache_size
        
        # Bounded storage for tables and reducers
        self.tables: Dict[str, BoundedTableCache] = {}
        self.reducer_cache = BoundedDict(
            max_size=1000,  # Reasonable limit for reducers
            memory_accountant=self.memory_accountant
        )
        
        # Load tables and reducers from autogen package
        self._load_autogen_package(autogen_package)
    
    def _load_autogen_package(self, autogen_package) -> None:
        """Load tables and reducers from autogenerated package."""
        try:
            for importer, module_name, is_package in pkgutil.iter_modules(
                autogen_package.__path__
            ):
                if not is_package:
                    module = importlib.import_module(
                        f"{autogen_package.__name__}.{module_name}"
                    )
                    
                    # Check if it's a reducer
                    if module_name.endswith("_reducer"):
                        reducer_name = getattr(module, "reducer_name", None)
                        args_class = getattr(module, "_decode_args", None)
                        
                        if reducer_name and args_class:
                            self.reducer_cache.set(reducer_name, args_class)
                            logger.debug(f"Loaded reducer: {reducer_name}")
                    else:
                        # Assuming table class name is the same as the module name
                        table_class_name = snake_to_camel(module_name)
                        
                        if hasattr(module, table_class_name):
                            table_class = getattr(module, table_class_name)
                            
                            # Check for a special property, e.g. 'is_table_class'
                            if getattr(table_class, "is_table_class", False):
                                self.tables[table_class_name] = BoundedTableCache(
                                    table_class,
                                    max_entries=self.max_cache_size,
                                    memory_accountant=self.memory_accountant
                                )
                                logger.debug(f"Loaded table: {table_class_name}")
        
        except Exception as e:
            logger.error(f"Failed to load autogen package: {e}")
    
    def get_table_cache(self, table_name: str) -> Optional[BoundedTableCache]:
        """Get table cache by name."""
        return self.tables.get(table_name)
    
    def decode(self, table_name: str, value: Any) -> Optional[Any]:
        """Decode a value for a specific table."""
        if table_name not in self.tables:
            logger.error(f"[decode] Table not found: {table_name}")
            return None
        
        try:
            return self.tables[table_name].decode(value)
        except Exception as e:
            logger.error(f"[decode] Failed to decode value for table {table_name}: {e}")
            return None
    
    def set_entry(self, table_name: str, key: Any, value: Any) -> bool:
        """Set an entry in a table cache."""
        if table_name not in self.tables:
            logger.error(f"[set_entry] Table not found: {table_name}")
            return False
        
        try:
            self.tables[table_name].set_entry(key, value)
            return True
        except Exception as e:
            logger.error(f"[set_entry] Failed to set entry for table {table_name}: {e}")
            return False
    
    def set_entry_decoded(self, table_name: str, key: Any, value: Any) -> bool:
        """Set an already decoded entry in a table cache."""
        if table_name not in self.tables:
            logger.error(f"[set_entry_decoded] Table not found: {table_name}")
            return False
        
        try:
            self.tables[table_name].set_entry_decoded(key, value)
            return True
        except Exception as e:
            logger.error(f"[set_entry_decoded] Failed to set decoded entry for table {table_name}: {e}")
            return False
    
    def delete_entry(self, table_name: str, key: Any) -> bool:
        """Delete an entry from a table cache."""
        if table_name not in self.tables:
            logger.error(f"[delete_entry] Table not found: {table_name}")
            return False
        
        return self.tables[table_name].delete_entry(key)
    
    def get_entry(self, table_name: str, key: Any) -> Optional[Any]:
        """Get an entry from a table cache."""
        if table_name not in self.tables:
            logger.error(f"[get_entry] Table not found: {table_name}")
            return None
        
        return self.tables[table_name].get_entry(key)
    
    def get_cache_stats(self) -> Dict[str, Any]:
        """Get comprehensive cache statistics."""
        memory_stats = self.memory_accountant.get_stats()
        
        table_stats = {}
        for table_name, table_cache in self.tables.items():
            table_stats[table_name] = table_cache.get_stats()
        
        return {
            'memory_usage': {
                'total_bytes': memory_stats.total_bytes,
                'cache_bytes': memory_stats.cache_bytes,
                'peak_bytes': memory_stats.peak_bytes,
                'evictions': memory_stats.evictions,
                'oom_prevented': memory_stats.oom_prevented,
                'usage_percentage': self.memory_accountant.get_usage_percentage()
            },
            'table_caches': table_stats,
            'reducer_cache': {
                'entry_count': len(self.reducer_cache)
            }
        }
    
    def clear_all_caches(self) -> None:
        """Clear all caches."""
        for table_cache in self.tables.values():
            table_cache.entries.clear()
        
        self.reducer_cache.clear()
        logger.info("All caches cleared")
    
    def cleanup_memory_pressure(self) -> Dict[str, int]:
        """Perform cleanup when under memory pressure."""
        cleared_counts = {}
        
        # Clear least important caches first
        for table_name, table_cache in self.tables.items():
            old_count = len(table_cache.entries)
            # Force eviction of half the entries by temporarily reducing size
            original_size = table_cache.entries._max_size
            table_cache.entries._max_size = original_size // 2
            table_cache.entries._evict_if_needed()
            table_cache.entries._max_size = original_size
            
            cleared_count = old_count - len(table_cache.entries)
            if cleared_count > 0:
                cleared_counts[table_name] = cleared_count
        
        return cleared_counts


# For backward compatibility, provide the same interface as the original client_cache
ClientCache = BoundedClientCache
TableCache = BoundedTableCache